name: Purge Writing On Update, Kitsune.Gay Edition

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ observability ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - uses: jakejarvis/s3-sync-action@master
#       with:
#         args: --acl public-read --follow-symlinks --delete --exclude '.git*'
#       env:
#         AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
#         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  AWSUpload:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.observe.outputs.result }}
    steps:
      - uses: actions/checkout@v2
      # - uses: jakejarvis/s3-sync-action@master
      - name: S3 Bucket 1 Upload

        id: s3bucket1
        run: |
          echo "this is a test"
      
      - id: observe
        run: echo "result=success" >> $GITHUB_OUTPUT

  # AWSUPLOAD2:
  #   name: AWSUpload2
  #   runs-on: ubuntu-latest
  #   steps:
  #       - uses: actions/checkout@v2
  #       - uses: jakejarvis/s3-sync-action@master
  #         name: S3 Bucket 2 Upload

  #         with:
  #           args: --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*' --exclude '.gitignore' --exclude 'package*' --exclude 'terraform/*' --exclude '.vscode/*'
  #         env:
  #           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET1 }}
  #           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #           AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1

  # AWSUPLOAD3:
  #   name: AWSUpload3
  #   runs-on: ubuntu-latest
  #   steps:
  #       - uses: actions/checkout@v2
  #       - uses: jakejarvis/s3-sync-action@master
  #         name: S3 Bucket 3 Upload

  #         with:
  #           args: --follow-symlinks --delete --exclude '.git/*' --exclude '.github/*' --exclude '.gitignore' --exclude 'package*' --exclude 'terraform/*'  --exclude '.vscode/*'
  #         env:
  #           AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET2 }}
  #           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #           AWS_REGION: 'us-west-1'   # optional: defaults to us-east-1


  FastlyPurge:
    name: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: report results
        run: echo ${{needs.AWSUpload.outputs.output1}}

      # - name: Install Fastly
      #   run: |
      #      curl -L https://github.com/fastly/cli/releases/download/v4.3.0/fastly_4.3.0_linux_amd64.deb > fastly_4.3.0_linux_amd64.deb
      #      sudo apt install ./fastly_*_linux_amd64.deb

      # - name: Purge
      #   run: |
      #       fastly purge --token=${{ secrets.FASTLY_PURGE_TOKEN }} --service-id=${{ secrets.SERVICE_ID }} --url=https://www.Kitsune.gay/Writing.html
      #       fastly purge --token=${{ secrets.FASTLY_PURGE_TOKEN }} --service-id=${{ secrets.SERVICE_ID }} --url=https://www.Kitsune.gay/Cast.html

